security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\Account\User:
            algorithm: auto
    role_hierarchy:
        ROLE_USER:
            - ROLE_DASHBOARD_PANEL
            - ROLE_TASK_LIST
            - ROLE_TASK_CREATE
            - ROLE_TASK_EDIT
            - ROLE_TASK_VIEW
            - ROLE_TASK_DELETE
            - ROLE_TASK_RUN
            - ROLE_MODEL_LIST
            - ROLE_MODEL_BUILD
            - ROLE_MODEL_EDIT
            - ROLE_MODEL_VIEW
            - ROLE_MODEL_DELETE
            - ROLE_MODEL_IMAGE
            - ROLE_MODEL_EXPORT
            - ROLE_MODEL_IMPORT
            - ROLE_BUG_LIST
            - ROLE_BUG_EDIT
            - ROLE_BUG_VIEW
            - ROLE_BUG_DELETE
            - ROLE_BUG_OPEN
            - ROLE_BUG_CLOSE
            - ROLE_BUG_VIDEO
            - ROLE_BUG_EXPORT
            - ROLE_BUG_REDUCE
        ROLE_SUPER_ADMIN:
            - ROLE_USER
            - ROLE_ACCOUNT_LIST
            - ROLE_ACCOUNT_EDIT
            - ROLE_ACCOUNT_PASSWORD
            - ROLE_ACCOUNT_ROLES
            - ROLE_ACCOUNT_GROUP
            - ROLE_ACCOUNT_DELETE
            - ROLE_ACCOUNT_ACTIVATE
            - ROLE_ACCOUNT_FREEZE
            - ROLE_GROUP_LIST
            - ROLE_GROUP_CREATE
            - ROLE_GROUP_EDIT
            - ROLE_GROUP_ROLES
            - ROLE_GROUP_DELETE
            - ROLE_ACTIVITY_HTTP
            - ROLE_ACTIVITY_MAIL
            - ROLE_CONFIG_GENERAL
            - ROLE_CONFIG_MEDIA
            - ROLE_CONFIG_USER
    providers:
        pdadmin_auth:
            entity:
                class: App\Entity\Account\User
                property: email

        pdadmin_api:
            entity:
                class: App\Entity\Account\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/(admin|testing|login|logout|register|resetting)
            provider: pdadmin_auth
            lazy: true
            user_checker: Pd\UserBundle\Security\UserChecker
            access_denied_handler: App\Security\AccessDeniedHandler
            switch_user: { role: CAN_SWITCH_USER }
            http_basic: ~
            form_login:
                use_referer: true
                login_path: security_login
                check_path: security_login
                default_target_path: "%app.login_redirect%"
            entry_point: form_login
            logout:
                path: security_logout
                target: '%app.logout_redirect%'
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 604800 # 1 Week - 1 Month -> 2592000
                path: /
        api:
            pattern: "%api.route%"
            stateless: true
            provider: pdadmin_api
            json_login:
                check_path: /api/auth/login
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            entry_point: lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        # Admin Panel
        - { path: '^/admin', role: ROLE_USER }
        - { path: '^/testing', role: ROLE_USER }

        # API
        #- { path: "%api.route%/doc", roles: PUBLIC_ACCESS }
        - { path: "%api.route%/auth", roles: PUBLIC_ACCESS }
        - { path: "%api.route%", roles: IS_AUTHENTICATED_FULLY }
