version: '3.4'

services:
    database:
        image: postgres:${POSTGRES_VERSION:-13}-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-user}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
            POSTGRES_DB: ${POSTGRES_DB:-db}
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: unless-stopped
        environment:
            ADMINER_DEFAULT_SERVER: database
        ports:
            - 8888:8080

    mailer:
        image: mailhog/mailhog:latest
        restart: unless-stopped
        ports:
            - 1025:1025
            - 8025:8025
        logging:
            driver: 'none'  # disable saving logs

volumes:
    postgres_data:
