version: '3.4'

services:
    database:
        image: postgres:${POSTGRES_VERSION:-13}-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-user}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
            POSTGRES_DB: ${POSTGRES_DB:-db}
        ports:
            - 5432:5432

    selenoid:
        image: aerokube/selenoid:latest-release
        volumes:
            - "$PWD/config/selenoid:/etc/selenoid"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "$PWD/config/selenoid/video:/opt/selenoid/video"
            - "$PWD/config/selenoid/logs:/opt/selenoid/logs"
        environment:
            - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/config/selenoid/video
        restart: unless-stopped
        command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "${CONTAINER_NETWORK:-sicope-model_default}"]
        ports:
            - "4444:4444"
