version: '3'

services:
    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: db
        ports:
            - 5432:5432

    adminer:
        image: adminer
        ports:
            - 8888:8080

    selenoid:
        network_mode: bridge
        image: aerokube/selenoid:latest-release
        volumes:
            - "$PWD/config/selenoid:/etc/selenoid"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "$PWD/config/selenoid/video:/opt/selenoid/video"
            - "$PWD/config/selenoid/logs:/opt/selenoid/logs"
        environment:
            - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/config/selenoid/video
        command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs" ]
        ports:
            - "4444:4444"

    selenoid-ui:
        network_mode: bridge
        image: "aerokube/selenoid-ui"
        ports:
            - "8080:8080"
        command: ["--selenoid-uri", "http://selenoid:4444"]
