version: '3'

services:
    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: db
        ports:
            - 5432:5432
