version: '3.4'

services:
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8888:8080

    mailer:
        image: mailhog/mailhog:latest
        restart: unless-stopped
        ports:
            - 1025:1025
            - 8025:8025

    selenoid-ui:
        image: "aerokube/selenoid-ui"
        restart: unless-stopped
        ports:
            - "8080:8080"
        command: ["--selenoid-uri", "http://selenoid:4444"]
