version: "3.4"

services:
  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - "8080:8080"

  mailer:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    logging:
      driver: 'none'  # disable saving logs

  selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/var/selenoid:/etc/selenoid"
      - "$PWD/var/selenoid/video:/opt/selenoid/video"
      - "$PWD/var/selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/var/selenoid/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "${CONTAINER_NETWORK:-sicope-model_default}"]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    ports:
      - "8081:8081"
    expose:
      - "8081"
    command: ["-listen", ":8081", "--selenoid-uri", "http://selenoid:4444"]

  database:
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./var/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  admin:
    image: tienvx/sicope-model-admin-debug:latest
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION}&charset=UTF-8
      STATUS_URI: http://selenoid:4444
      WEBDRIVER_URI: http://selenoid:4444
      MAILER_DSN: smtp://mailer:1025
      DB_EXTENSION: Postgresql
      MESSENGER_TRANSPORT_DSN: redis://redis:6379/messages
      REDIS_DSN: redis://redis:6379
    depends_on:
      - database
      - redis
    #volumes:
    #  - .:/srv/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    image: tienvx/sicope-model-worker-debug:latest
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION}&charset=UTF-8
      WEBDRIVER_URI: http://selenoid:4444
      MAILER_DSN: smtp://mailer:1025
      DB_EXTENSION: Postgresql
      MESSENGER_TRANSPORT_DSN: redis://redis:6379/messages
      REDIS_DSN: redis://redis:6379
    depends_on:
      - database
      - redis
    #volumes:
    #  - .:/srv/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  caddy:
    image: tienvx/sicope-model-caddy:latest
    depends_on:
      - admin
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
      PHP_FPM_ADDRESS: admin:9000
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    #volumes:
    #  - ./public:/srv/app/public
