version: "3.4"

x-php: &php
  volumes:
    # The "cached" option has no effect on Linux but improves performance on Mac
    - ./:/srv/app:rw,cached
    - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
    # If you develop on Mac you can remove the var/ directory from the bind-mount
    # for better performance by enabling the next line
    # - /srv/app/var
  environment:
    APP_ENV: dev

# Development environment override
services:
  admin:
    <<: *php
  worker:
    <<: *php

  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv/app/public:ro

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - "8888:8080"

  mailer:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    logging:
      driver: 'none'  # disable saving logs

  selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/var/selenoid:/etc/selenoid"
      - "$PWD/var/selenoid/video:/opt/selenoid/video"
      - "$PWD/var/selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/var/selenoid/video
    restart: unless-stopped
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "${CONTAINER_NETWORK:-sicope-model_default}"]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
