version: '3.4'

services:
  admin:
    image: tienvx/sicope-model-admin:${TAG:-lastest}
    build:
      context: .
      target: build_admin
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-pass}@${POSTGRES_HOST:-database}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-db}?serverVersion=${POSTGRES_VERSION:-13}&charset=UTF-8
      STATUS_URI: ${STATUS_URI:-http://selenoid:4444}
      MAILER_DSN: ${MAILER_DSN:-smtp://mailer:1025}
      DB_EXTENSION: Postgresql

  worker:
    image: tienvx/sicope-model-worker:${TAG:-lastest}
    build:
      context: .
      target: build_worker
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-pass}@${POSTGRES_HOST:-database}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-db}?serverVersion=${POSTGRES_VERSION:-13}&charset=UTF-8
      WEBDRIVER_URI: ${WEBDRIVER_URI:-http://selenoid:4444}
      MAILER_DSN: ${MAILER_DSN:-smtp://mailer:1025}
      DB_EXTENSION: Postgresql

  caddy:
    image: tienvx/sicope-model-caddy:${TAG:-lastest}
    build:
      context: .
      target: build_caddy
    depends_on:
      - admin
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp

volumes:
  php_socket:
  caddy_data:
  caddy_config:
