version: '3.4'

services:
    postgres:
        image: postgres:${POSTGRES_VERSION:-13}-alpine
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-user}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
            POSTGRES_DB: ${POSTGRES_DB:-db}
        ports:
            - 5432:5432

    selenoid:
        network_mode: bridge
        image: aerokube/selenoid:latest-release
        volumes:
            - "$PWD/config/selenoid:/etc/selenoid"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "$PWD/config/selenoid/video:/opt/selenoid/video"
            - "$PWD/config/selenoid/logs:/opt/selenoid/logs"
        environment:
            - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/config/selenoid/video
        command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs" ]
        ports:
            - "4444:4444"

    admin:
        image: tienvx/sicope-model-admin
        build:
            context: .
            target: admin
        depends_on:
            - postgres
        environment:
          DATABASE_URL: postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-pass}@postgres:5432/${POSTGRES_DB:-db}?serverVersion=${POSTGRES_VERSION:-13}&charset=UTF-8

    worker:
        image: tienvx/sicope-model-worker
        build:
            context: .
            target: worker
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-pass}@postgres:5432/${POSTGRES_DB:-db}?serverVersion=${POSTGRES_VERSION:-13}&charset=UTF-8

    caddy:
        build:
            context: .
            target: caddy
        depends_on:
            - admin
        environment:
            SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - caddy_data:/data
            - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
