##
# Authorization
##
authorization:
    resource: "@PdUserBundle/Resources/config/routing.yaml"

##
# Admin
##
admin:
    resource: ../src/Controller/
    type: annotation
admin_widget:
    resource: "@PdWidgetBundle/Resources/config/routing.yml"
admin_mailer:
    resource: "@PdMailerBundle/Resources/config/routing.yaml"
