when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
    web_profiler_wdt:
        resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
        prefix: /_wdt

    web_profiler_profiler:
        resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
        prefix: /_profiler


#------------------------------------
# Admin
#------------------------------------
auth:
    resource: "@PdUserBundle/Resources/config/routing.yaml"

admin:
    resource: ../src/Controller/Admin
    type: annotation
    prefix: 'admin'
admin_widget:
    resource: "@PdWidgetBundle/Resources/config/routing.yml"
    prefix: 'admin'
redirect_home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: security_login
        permanent: true


#------------------------------------
# API
#------------------------------------
api:
    resource: ../src/Controller/Api
    type: annotation
    prefix: api

#------------------------------------
# Testing
#------------------------------------
testing:
    resource: ../src/Controller/Testing
    type: annotation
    prefix: 'testing'
