imports:
    - { resource: "defaults.yaml" }

parameters:
    container.dumper.inline_factories: true
    container.dumper.inline_class_loader: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Widgets,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Load Widgets
    App\Widgets\:
        resource: '../src/Widgets/*'
        tags:
            - { name: kernel.event_listener, event: widget.start, method: builder }

    Pd\UserBundle\Configuration\ConfigInterface: '@App\Service\ConfigBag'

    Tienvx\Bundle\MbtBundle\Generator\RandomGenerator:
        class: App\Model\RandomGenerator

    Tienvx\Bundle\MbtBundle\Service\Bug\BugNotifierInterface:
        class: App\Service\BugNotifier
        bind:
            $mailSenderAddress: '%mail_sender_address%'
            $mailSenderName: '%mail_sender_name%'
